### ISSUE TITLE
Reaction roles

### ISSUE THREAD

**Issue by EricLottman** [AJGherardi/ManageBot#7]
A feature where the bot gives a role based on a reaction.  
So essentially the bot sends a message describing whatever message you did you desire. Then you tell it a reaction to add to the message. Afterwards you give the bot a role to associate with that reaction to that message. If a user clicks the reaction they receive the role, and if they remove the reaction the role is removed. The bot should be able to add multiple role options to one message and the message should be hopefully customizable. A good way to go about that is making your own message and giving the bot the message ID. The bot should be able to remove any reaction that aren't intended for reaction roles on messages solely meant for reaction roles. A way to delete reaction roles would be necessary too

**Comment by AJGherardi** [comment]
Users do not get to see the ID of a message. So we cant watch for roles on existing messages.

**Comment by AJGherardi** [comment]
Will be a subcommand of the say command.
